export const clubLogos: { [key: string]: string } = {
  ars: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t3.png",
  avl: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t7.png",
  bou: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t91.png",
  bre: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t94.png",
  bha: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t36.png",
  che: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t8.png",
  cry: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t31.png",
  eve: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t11.png",
  ful: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t54.png",
  ips: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t40.png",
  lei: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t13.png",
  liv: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t14.png",
  mci: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t43.png",
  mun: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t1.png",
  new: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t4.png",
  nfo: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t17.png",
  sou: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t20.png",
  tot: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t6.png",
  whu: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t21.png",
  wol: "https://s3.amazonaws.com/premierleague-static-files/premierleague/badges/100/t39.png",
};
